version: "3.7"

services:
  postfix:
    build: .
    image: schoolscout/postfix-mail-gateway
    ports:
      - "25:25"
    env_file: .env
    # optional
    #volumes:
      #- /etc/hostname:/etc/mailhostname:ro
