version: "3.7"

services:
  postfix:
    build: .
    image: schoolscout/postfix-mail-gateway:0.2.0
    ports:
      - "25:25"
    env_file: .env
    # optional
    volumes:
      #- /etc/hostname:/etc/mailhostname:ro
      - ./ca/out/Test_CA.crt:/run/secrets/cacert.pem:ro
      - ./ca/out/smtp-relay.perspective-daily.de.key:/run/secrets/smtpd.key:ro
      - ./ca/out/smtp-relay.perspective-daily.de.crt:/run/secrets/smtpd.crt:ro
